name: mobile_beta
description: "Beta AI speaking practice system for scenario-based intercultural English learning."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  cupertino_icons: ^1.0.8
  camera: ^0.12.0+1
  speech_to_text: ^7.4.0
  flutter_tts: ^4.2.5
  shared_preferences: ^2.5.5
  audioplayers: ^6.0.0
  o3d: ^3.1.0
  google_fonts: ^6.2.0
  mobile_scanner: ^7.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/models/male_char.glb
    - assets/models/female_char.glb
    - assets/models/olivia_animated.glb
    - assets/models/sarah_animated.glb
    - assets/models/dr_emma_animated.glb
    - assets/models/hr_animated.glb
